name: TG Parser

on:
  schedule:
    - cron: '*/15 * * * *'   # каждые 5 минут
  workflow_dispatch:          # ручной запуск через кнопку в интерфейсе

jobs:
  parse:
    runs-on: ubuntu-latest
    timeout-minutes: 20       # принудительно убивает если завис

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parser
        env:
          TG_API_ID:                ${{ secrets.TG_API_ID }}
          TG_API_HASH:              ${{ secrets.TG_API_HASH }}
          TG_SESSION:               ${{ secrets.TG_SESSION }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          SPREADSHEET_IDS:          ${{ secrets.SPREADSHEET_IDS }}
          MESSAGES_LIMIT:           '10'
        run: python main.py
